version: "3.8"
services:
  database:
    image: "postgres:14"
    restart: always
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5442:5432"
volumes:
  psql-data:
    driver: local
